#include "mytypes.h"
#include "glbdef.h"

// Automagically generated by enummaker.exe.
// DO NOT EDIT THIS FILE (Yes, I mean you!)


// Definitions for MOB
const struct MOB_DEF
glb_mobdefs[NUM_MOBS] =
{
  {
    '@',
    ATTR_WHITE,
    1,
    10,
    255,
    100,
    "You",
  },
  {
    'i',
    ATTR_DKRED,
    1,
    1,
    4,
    100,
    "Imp",
  },
  {
    'a',
    ATTR_RED,
    1,
    1,
    2,
    2,
    "Ant",
  },
  {
    'o',
    ATTR_GREEN,
    2,
    2,
    6,
    100,
    "Orc",
  },
  {
    'r',
    ATTR_LIGHTBLACK,
    1,
    1,
    1,
    1,
    "Rat",
  },
  {
    'b',
    ATTR_YELLOW,
    1,
    1,
    3,
    5,
    "Bee",
  },
  {
    'e',
    ATTR_WHITE,
    1,
    1,
    5,
    5,
    "Elf",
  },
  {
    '@',
    ATTR_PURPLE,
    3,
    3,
    10,
    10,
    "Wiz",
  },
};

// Definitions for TILE
const struct TILE_DEF
glb_tiledefs[NUM_TILES] =
{
  {
    '#',
    ATTR_BROWN,
    false,
    false,
  },
  {
    '.',
    ATTR_NORMAL,
    true,
    true,
  },
  {
    '>',
    ATTR_NORMAL,
    true,
    true,
  },
  {
    '$',
    ATTR_GOLD,
    true,
    true,
  },
  {
	'!',
	  ATTR_NORMAL,
	  true,
	  true,
  },
};

// Definitions for ATTR
const struct ATTR_DEF
glb_attrdefs[NUM_ATTRS] =
{
  {
    255,
    196,
    0,
  },
  {
    255,
    255,
    0,
  },
  {
    192,
    192,
    192,
  },
  {
    96,
    96,
    96,
  },
  {
    96,
    96,
    96,
  },
  {
    255,
    255,
    255,
  },
  {
    192,
    128,
    64,
  },
  {
    255,
    32,
    32,
  },
  {
    196,
    32,
    32,
  },
  {
    0,
    255,
    0,
  },
  {
    255,
    0,
    196,
  },
};
